frontend
oliverye7/vim_finesse pull request #7
Opened 2023-12-05 03:45 UTC by oliverye7

1. set up basic frontend routes (/login, /play, /home) without any css styling
2. connect frontend to backend
3. update backend to allow CORS from localhost, remove /proto directory

2023-12-05 04:48 UTC, rahulk29 commented on backend/src/api/challenge.rs
> +    //};
delete?

2023-12-05 04:52 UTC, rahulk29 approved these changes

2023-12-05 05:04 UTC, seany4ng requested changes
only blocking changes are to revive the `.gitignore` in backend so the next PR doesn't add a bunch of random shit, and remove `/src/index.html` before we forget that it's useless. rest lgtm

2023-12-05 05:04 UTC, seany4ng commented on client/src/index.html
delete this file

2023-12-05 07:28 UTC, oliverye7 commented on client/nginx/nginx.conf
its literally "nginx" tho
https://nginx.org/en/

2023-12-05 07:49 UTC, seany4ng commented on client/nginx/nginx.conf
but what is it being used for rn, i don't see any references to this in the actual code

2023-12-06 23:20 UTC, oliverye7 commented on client/src/components/Home/Body.js
> +    </div>
yeah this is going to all go in the `tailwind.config` file which should be created already, haven't decided on site colors yet so for now we'll keep that mostly empty 

right now `tailwind.config` just contains the font karla that i blanket applied cuz i used it for my other site

2023-12-24 00:17 UTC, seany4ng approved these changes

2023-12-24 00:17 UTC, merged